config/routes.rb
Rails.application.routes.draw do


  get 'users/new'
  root 'static_pages#home'

  get '/help',    to:   'static_pages#help'
  get '/about',   to:   'static_pages#about'
  get '/contact', to:   'static_pages#contact'
  get '/signup',  to:   'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255 },
		format: { with: VALID_EMAIL_REGEX },
		uniqueness: true
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


	def User.digest(string)
       cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST
:			BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end	

	#returns a random token.
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# remembers a userin the database for use in persistent sessions.
	def remember 
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end
	
	# Retrns true if the given token matches the digest.
	def autheticated? (remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(rememer_digest).is_password?(remember_token)
	end


	#forgets a user
	def forget
		update_attribue(:remember_digest, nil)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
	  ?user = User.find_by(email: params[:session][:email].downcase)
	  if user && user.authenticate(params[:session][:password])
	  log_in user
	params[:session][:remember_me] == '1'? remember(user) :forget(user)
	redirect_back_or user
	 else 
	    flash.now[:danger] = 'Invalid email/password combnation' #not quiteright
	 render 'new'
	end
	end


	def destroy
	  log_out if logged_in?
	  redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action: admin_user, 	only: :destroy
  def index
    @users = User.paginate(page: paras[:page])
  end


  def show
	@user = User.find(params[:id])

end

  def new
	@user = User.new
  end

  def create
	  @user = User.new(user_params) 

	if @user.save
	   log_in @user
		flash[:success]= "Welcome to the Sameple App!"
		redirect_to @user
	else
	  render 'new'
	end
  end
 
  def edit 
	  @user = User.find(params[:id])
  end


  def update 
	  @user = User.find(params[:id])
	  if @user.update(user_params)
	      flash[:success] = "Profile updated"
	      redirected_to @user
	  else 
		  render 'edit'
	  end
  end

  def destory
	  User.find(params[:id]).destroy
	  flash[:success] = "User deleted"
	  redirect_to users_url
  end


  private

  def user_params
	  params.require(:user).permit(:name, :email, :password,
				       :password_confirmation)
  end


  def logged_in_user
	  unless logged_in?
		  store_location
		  flash[:danger] = "Please log in."
		  redirect_to login_url
	  end
  end


  def correct_user
	  @user = User.find(params[:id])
	  redirect_to(root_url) unless curent_user?(@user)
  end


  # Confirms an admin user
  def admin user
	  redirect_to(root_url) unless current_user.admi?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on a  per-page basesl
	def full_title(page_title = '')
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else 
		   page_title + " | " + base_title
		end 
	end 
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
	  session[:user_id] = user.id
  end

  def remember(user)
	  user.remember
	  cookies.permanant.encrypted[:user_id] = user.id
	  cookies.permanet[:remember_token] = user.remember_token
  end


  def current_user
	  if (user_id = session[:user_id])
	    @current_user ||= User.find_by(id: user_id)
	    elsif (user_id = cookies.encrypted[:user_id])
user = User.find_by(id: user_id)
	    if user && user.authenticated?(cookies[:remember_token])
		    log_in user
		    @current_user = user
	    end
	  end

  end

# Returns true if the given user is the current user.
  def current_user?(user)
	  user && user == current_user
  end



  def logged_in?
	  !current_user.nil?
  end

  # forgets a persistent session
  def forget(user)
	  user.forget
	  cookies.delete(:user_id)
	  cookies.delete(:remember_token)
  end


  # logs out the current user.
  def log_out
	  forget(curret_user)
	 session.delete(:user_id)
	 @current_user = nil
  end
 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	#Returns the Gravatar for the given user.
	def gravatar_for(user, size: 80)
 	gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
	gravatar_url = 
"https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
   end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
   <small>
     The <a href="https://www.railstutorial.org/">Ruby on Rails
Tutorial</a>
     by <a href="https:/www.michaelhartl.com/">Michael Hartl</a>
   </small>
   <nav>
	   <ul>
	      <li><%= link_to "About",   about_path  %></li>
	      <li><%= link_to "Contact", contact_path  %></li>
<li><a href="https://news.railstutorial.org/">News</a><li>
	   </ul>
   </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
	   <%= link_to "sample app", root_path, id: "logo" %>
	   <nav>
	     <div class="nvbr-header">
		<button type="button" class="navbar-toggle colapsed"
			data-toggle="collapse"
   			data-target="#bs-example-navbar-collapse-1"
      			aria-expanded="false">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></san>
		<span clas="icon-bar"></span>
		</button>
	     </div>
	      <ul class="nav navbar-nav navbar-right collapse navbar-collapse" id="bs-example-navbar-colase-1">
		 <li><%= link_to "Home",   root_path %></li>
		 <li><%= link_to "Help",   help_path %></li>
		 <% if logged_in? %>
		   <li><%= link_to "Users", users_path  %></li>
<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		Account <b class="caret"></b>
	</a>
	      </ul class="dropdown-menu">
	      <li><%= link_to "Profile", current_user %></li>
	      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
<li class="divider"></li>
		<li>
		   <%= link_to "Log out", logout_path, method: :delete %>
</li>
 		</ul>
		</li>
	<% else %>
	    <li><%= link_to "Log in", login_path %></li>
    <% end %>
 </ul>
	   </nav>
	</div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all',
                                       'data-turbolinks-
track': 'reload' %>
	 <%= javascript_pack_tag 'application', 'data-turbolinks
track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
     <script
src="//cdnjs.cloudfare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
	  <%= render 'layouts/header' %>
	  <div class="container">
		  <% flash.each do |message_type, message| %>
			  <%= content_tag(:div, message, class: "alert alert-
		     #{message_type}") %>
	     <% end %>

	       <%= yield %>
	       <%= render 'layouts/footer' %>
      		<%= debug(params) if Rails.env.development? %>
       </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
     <div class=".field_with_errors">
	 The form contains <%= pluralize(@user.errors.count, "error")
	 %>.
     </div>
     <ul>
     <% @user.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
     <% end %>
      </ul>
   </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
	  <title><% yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
	
      <h1>About</h1>
      <p>
         The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
         Tutorial</em></a>, part of the
         <a href="https://www.learnenough.com/">Learn Enough</a> family of
         tutorials, is a
         <a href="https://www.railstutorial.org/book">book</a> and
         <a href="https://screencasts.railstutorial.org/">screencast series</a> 
         to teach web development with
         <a href="https://rubyonrails.org/">Ruby on Rails</a>.
         This is the sample app for the tutorial.
     </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the 
    <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
   <head>
	   <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
   </head>
   <body>
      <h1>Help</h1>
      <p>
         Get help on the Ruby on Rails Tutorial at the 
         <a href="https://www.railstutorial.org/help">Rails Tutorial Help page</a>.
  	
  To get help on this sample app, see the <a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
	  book</a>
      </p>
   </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Welcome to the Sample App</h1>

	<h2>
           This is the home page for the 
          <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial </a>
	  sample application.
	</h2>

	<%= link_to "Sign up now!" , signup_path, class: "btn btn-lg btn-primary"
%>
</div>

<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"),
	"https://rubyonrails.org/" %>

<%#= image_tag("kitten.jpg", alt: "kitten") %> 

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
	<%= render 'shared/error_messages', object: @user %>
	
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :email %>
	<%= f.email_field :email, class: 'form-control' %>


	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>

	<%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 50 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "delete", user, method: :delete,
					data: { confirm: "You sure?" } %>
			<% end %>

</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changed') %>
<h1>Update your profile</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= gravatar_for @user %>
		<a href="https://gravatar.com/emails" target="_blank">Change</a>
	</div>
</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>
<ul class="users">
     <%= render user %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, "Create my account') %>
<h1>Sign up</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%=render 'form' %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
	  <%= gravatar_for @user %>
	  <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>